#!/bin/sh
# WARNING: REQUIRES /bin/sh
#
# - must run on /bin/sh on solaris 9
# - must run on /bin/sh on AIX 6.x
# - if you think you are a bash wizard, you probably do not understand
#   this programming language.  do not touch.
# - if you are under 40, get peer review from your elders.
#
PROGNAME=`basename $0`

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

for name in ruby bundle irb gem rake
do
  ln -sf /opt/chef/embedded/bin/$name /opt/chef/bin || error_exit "Cannot link $name to /opt/chef/bin"
done

echo "Thank you for installing Chef Foundation!"

exit 0
